### ISSUE TITLE
Trigger Delay

### ISSUE THREAD

**Issue by besimhu** [craftcms/webhooks#26]
We have webhooks in place with Sprout forms that send the data to Zapier. What I have noticed is that the hook does take place, but there seems to be some sort of delay where the webhook is not triggered until an admin logs in. 

Take a look at these post dates, they all happen at the same time for batches: https://d.pr/i/qkYKU6

**Comment by jasonmccallister** [comment]
@besimhu thank you for reporting this issue. This is most likely occuring because webhooks uses the queue underneath and when admins login, the queue is ran through an web request. As a side note, Andrew Welch has a great write up about queues here: https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms.

A good way to work around this would be to run the queue as a separate process. There is a configuration change as well as additional instructions on how to run the queue here: https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically
