### ISSUE TITLE
Advice on configuration for static site generation

### ISSUE THREAD

**Issue by weotch** [craftcms/webhooks#29]
I was hoping to get some advice on how to best use webhooks to trigger a new static build at Netlify whenever content changes.  I'm coming from a Contentful background where my configuration looks like this:

![Screen Shot 2020-04-22 at 4 49 56 PM](https://user-images.githubusercontent.com/77567/80044424-4e8e8280-84b9-11ea-9bdc-a541046cf409.png)

I want to trigger a rebuild on **any** change of content, whether it's a creating a new entry, an update, a bulk change, a re-order in a list, a change of publish status, a delete, etc.  The only thing I don't want to trigger the webhook for is changes to drafts, autosaves, or non-enabled entries; essentially anything that isn't ready for production.

1. Is there a single "Sender Class" and "Event Name" that captures all of that?
2. What should the Event Filters be set to?

I think this is useful for anyone using Craft headlessly with a static site generator.

Thanks!

**Comment by brandonkelly** [comment]
You would need to set this up as two separate webhooks – one for element saves, and one for deletes.

Both of them could use the `craft\base\Element` class, and the event names would be `afterSave` and `afterDelete`.

**Comment by weotch** [comment]
Thanks!  And would these be all just up the middle?  It's been unclear to me what the 3 statuses mean.

![Screen Shot 2020-06-18 at 12 51 09 PM](https://user-images.githubusercontent.com/77567/85065645-62c1c980-b162-11ea-9f91-fbe73b982cff.png)

**Comment by brandonkelly** [comment]
That’s explained here: https://github.com/craftcms/webhooks#filtering-events

> The only thing I don't want to trigger the webhook for is changes to drafts, autosaves, or non-enabled entries; essentially anything that isn't ready for production.

So in your case you’d want to set the filters up like so:

![An example Event Filters setting](https://user-images.githubusercontent.com/47792/85068333-175dea00-b167-11ea-81c5-7074363b5150.png)

In other words, only trigger the webhook when all of the following are true:

- The element is enabled
- The element is **not** a draft
- The element is **not** a revision
- The element is **not** being propagated

Note that the “Element is enabled” filter was just added in v2.3.1, so you will need to update to get access to that.

Assuming no actual element info is needed to be sent along with the webhook, you should give each of your webhooks a Debouncing Key Format of something like `element`, so that multiple element saves in the same request don’t result in multiple webhook requests.

**Comment by weotch** [comment]
Ha it really was _just_ added, wasn't it?  Thanks!!
